<a href="https://colab.research.google.com/github/Yehor-Makeiev/dataHW1/blob/main/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
# Task 1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

import numpy as np
vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
# Task 2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

arr = np.zeros((3, 3), dtype=int)
print(arr)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [39]:
# Task 3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

rand = np.random.randint(1, 11, (5, 5,))
print(rand)

[[ 2  8  4  3  3]
 [10  1  7 10  1]
 [ 5 10  8  6  2]
 [ 5  9  5  2  1]
 [ 9  6  6  8  9]]


In [40]:
# Task 4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

rand_fl = np.random.rand(4, 4)
print(rand_fl)

[[0.91556927 0.339196   0.78740414 0.45273089]
 [0.91939674 0.08535521 0.97633708 0.83491296]
 [0.82636798 0.54638228 0.0941508  0.81174017]
 [0.3245458  0.81745468 0.05286016 0.66242971]]


In [41]:
# Task 5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими
# цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

arr_1 = np.random.randint(1, 11, 5)
arr_2 = np.random.randint(1, 11, 5)
print(arr_1)
print(arr_2)

print(f'\naddition:\n{arr_1 + arr_2}')
print(f'\nsubtraction:\n{arr_1 - arr_2}')
print(f'\nmultiplication:\n{arr_1 * arr_2}')


[ 1  4 10  8  7]
[1 5 7 5 6]

addition:
[ 2  9 17 13 13]

subtraction:
[ 0 -1  3  3  1]

multiplication:
[ 1 20 70 40 42]


In [42]:
# Task 6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
import numpy as np
vec_1 = np.random.rand(7)
vec_2 = np.random.rand(7)
print(vec_1)
print(vec_2)

scal = np.dot(vec_1, vec_2)
print(f'\nscalar {scal}')


[0.20337798 0.84066942 0.74177078 0.31743121 0.97959499 0.70357809
 0.32209052]
[0.77879944 0.60182228 0.52614943 0.4471478  0.21180674 0.09348569
 0.37549595]

scalar 1.590748172066612


In [43]:
# Task 7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
import numpy as np

matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 3))
print(f'matrix 1: \n{matrix_1}')
print(f'matrix 2: \n{matrix_2}')

c = np.dot(matrix_1, matrix_2)
print(f'\n result: \n{c}')

matrix 1: 
[[7 6]
 [1 1]]
matrix 2: 
[[1 1 7]
 [8 5 6]]

 result: 
[[55 37 85]
 [ 9  6 13]]


In [44]:
# Task 8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
import numpy as np

matrix_1 = np.random.randint(1, 11, (3, 3))
print(f'\nmatrix 1: {matrix_1}')

inverse_matrix = np.linalg.inv(matrix_1)
print(f'\ninverse: {inverse_matrix}')




matrix 1: [[ 9  3  9]
 [ 7 10  1]
 [ 8  3  8]]

inverse: [[ 4.27777778e+00  1.66666667e-01 -4.83333333e+00]
 [-2.66666667e+00  8.68870193e-17  3.00000000e+00]
 [-3.27777778e+00 -1.66666667e-01  3.83333333e+00]]


In [45]:
# Task 9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
import numpy as np

matrix_1 = np.random.rand(4, 4)
print(matrix_1)

matrix_t = matrix_1.T
print(f'\n trans: \n{matrix_t}')


[[0.11732981 0.69186579 0.03077642 0.99095251]
 [0.74665442 0.95564088 0.05564888 0.1791352 ]
 [0.63182243 0.64639197 0.72831997 0.51602778]
 [0.48562074 0.85242645 0.83022442 0.0908626 ]]

 trans: 
[[0.11732981 0.74665442 0.63182243 0.48562074]
 [0.69186579 0.95564088 0.64639197 0.85242645]
 [0.03077642 0.05564888 0.72831997 0.83022442]
 [0.99095251 0.1791352  0.51602778 0.0908626 ]]


In [46]:
# Task 10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
import numpy as np
matrix_1 = np.random.randint(1, 11, (3, 4))
print(f'\nmatrix : \n{matrix_1}')
arr_1 = np.random.randint(1, 11, 4)
print(f'\narray: \n{arr_1}')

c = np.dot(matrix_1, arr_1)
print(f'\nmultiplicationy: \n{c}')



matrix : 
[[3 8 4 4]
 [5 8 7 2]
 [1 1 9 6]]

array: 
[ 9  5  2 10]

multiplicationy: 
[115 119  92]


In [47]:
# Task 11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
import numpy as np
matrix_1 = np.random.rand(2, 3)
print(f'\nmatrix : \n{matrix_1}')
arr_1 = np.random.rand(3)
print(f'\narray: \n{arr_1}')

c = np.dot(matrix_1, arr_1)
print(f'\nmultiplicationy: \n{c}')


matrix : 
[[0.21763465 0.81620692 0.33981891]
 [0.25482202 0.58514246 0.82591073]]

array: 
[0.70178941 0.65208217 0.23405906]

multiplicationy: 
[0.76450536 0.75370425]


In [53]:
# Task 12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення
import numpy as np

matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))
print(f'\nmatrix 1: \n{matrix_1}')
print(f'\nmatrix 2: \n{matrix_2}')

res = matrix_1 * matrix_2
print(f'\nresult: \n{res}')



matrix 1: 
[[9 4]
 [8 4]]

matrix 2: 
[[6 4]
 [6 4]]

result: 
[[54 16]
 [48 16]]


In [54]:
# Task 13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
import numpy as np

matrix_1 = np.random.randint(1, 11, (2, 2))
matrix_2 = np.random.randint(1, 11, (2, 2))
print(f'\nmatrix 1: \n{matrix_1}')
print(f'\nmatrix 2: \n{matrix_2}')

res = np.dot(matrix_1, matrix_2)
print(f'\nresult: \n{res}')



matrix 1: 
[[3 3]
 [3 9]]

matrix 2: 
[[ 7 10]
 [10  9]]

result: 
[[ 51  57]
 [111 111]]


In [55]:
# Task 14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
import numpy as np
matrix_1 = np.random.randint(1, 101, (5, 5))
print(f'\nmatrix 1: \n{matrix_1}')

s = np.sum(matrix_1)
print(f'\nsum: \n{s}')



matrix 1: 
[[38  8 61 64 99]
 [73 45 65 63 83]
 [42 32 72 25 34]
 [72 87 69 63 55]
 [91 25 10 46 76]]

sum: 
1398


In [56]:
# Task 15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
import numpy as np

matrix_1 = np.random.randint(1, 11, (4, 4))
matrix_2 = np.random.randint(1, 11, (4, 4))
print(f'\nmatrix 1: \n{matrix_1}')
print(f'\nmatrix 2: \n{matrix_2}')

res = matrix_1 - matrix_2
print(f'\ndiff: \n{res}')



matrix 1: 
[[2 3 3 3]
 [7 8 3 9]
 [1 5 9 7]
 [6 5 8 6]]

matrix 2: 
[[5 6 8 5]
 [1 4 1 4]
 [2 6 4 9]
 [5 5 2 8]]

diff: 
[[-3 -3 -5 -2]
 [ 6  4  2  5]
 [-1 -1  5 -2]
 [ 1  0  6 -2]]


In [60]:
# Task 16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та
# знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
import numpy as np

matrix_1 = np.random.rand(3, 3)
print(f'\nmatrix 1: \n{matrix_1}')
sum_v = np.sum(matrix_1, axis=1).reshape(-1, 1)
print(f'\n result: \n{sum_v} ')


matrix 1: 
[[0.13590726 0.66003625 0.58789312]
 [0.25233799 0.20315099 0.31305777]
 [0.10850485 0.40073664 0.50272596]]

 result: 
[[1.38383663]
 [0.76854675]
 [1.01196745]] 


In [61]:
# Task 17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
import numpy as np

matrix_1 = np.random.randint(1, 11, (3, 4))
print(f'\nmatrix 1: \n{matrix_1}')

sq = matrix_1 ** 2
print(f'\n squared: \n {sq}')



matrix 1: 
[[10  9  2  7]
 [ 8  4  2  7]
 [ 6  9 10  1]]

 squared: 
 [[100  81   4  49]
 [ 64  16   4  49]
 [ 36  81 100   1]]


In [64]:
# Task 18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
import numpy as np
vec_1 = np.random.randint(1, 51 , 5)
print(f'\nvector: \n{vec_1}')
sq = np.sqrt(vec_1)
print(f'\n squared: \n {sq}')




vector: 
[42  8 45 46 43]

 squared: 
 [6.4807407  2.82842712 6.70820393 6.78232998 6.55743852]
